name: CI

on:
    schedule:
        # Every sunday at 02:00
        - cron: 0 2 * * 0
    pull_request:
    push:

jobs:
    ci:
        name: CI PHP ${{ matrix.php }} (Symfony ${{ matrix.symfony }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                symfony:
                    - '4.4.*'
                    - '5.1.*'
                coverage:
                    - none
                include:
                    - php: '7.4'
                      symfony: '5.1.*'
                      bootable: true
                      coverage: pcov
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Check commit messages
              uses: wagoid/commitlint-github-action@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  ini-values: pcov.directory=.
                  coverage: ${{ matrix.coverage }}

            - name: Get Composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Configure Symfony
              run: composer config extra.symfony.require "${{ matrix.symfony }}"

            - name: Update project dependencies
              run: composer update --no-progress --ansi --prefer-stable

            - name: Bundle is bootable
              if: matrix.bootable
              env:
                  SKELETON_VERSION: ${{ matrix.symfony }}
              run: |
                  composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
                  cd flex
                  composer config extra.symfony.allow-contrib true
                  composer req tilleuls/url-signer-bundle league/uri-components:2.x-dev
                  cd ..
                  rm -rf flex

            - name: Check code style
              if: matrix.php != '8.0' # To remove when PHP 8.0.1 is used
              run: vendor/bin/php-cs-fixer fix --ansi --diff --dry-run

            - name: Analyze code (Psalm)
              run: vendor/bin/psalm --long-progress --output-format=github --shepherd --stats

            - name: Analyze code (PHPStan)
              run: vendor/bin/phpstan analyze . --ansi --no-progress --error-format=github

            - name: Run functional tests
              run: vendor/bin/behat --colors

            - name: Run unit tests
              if: matrix.coverage == 'none'
              run: vendor/bin/phpunit --colors=always --testdox

            - name: Run unit tests with coverage
              if: matrix.coverage != 'none'
              run: vendor/bin/phpunit --coverage-clover=clover.xml --coverage-xml=coverage-xml --log-junit=junit.xml --colors=always --testdox

            - name: Upload coverage results
              if: matrix.coverage != 'none'
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  composer global require --no-progress --no-suggest --ansi cedx/coveralls
                  export PATH="$PATH:$HOME/.composer/vendor/bin"
                  coveralls ./clover.xml

            - name: Run mutation testing
              if: matrix.coverage != 'none'
              env:
                  INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
              run: vendor/bin/infection --ansi --skip-initial-tests --coverage=. --logger-github
